config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: %i[index show update] do
    resources :friendships, only: %i[create]
  end

  resources :friendships, only: %i[update]

  resources :posts, only: %i[index show new create] do
    resources :comments, only: %i[show new create]
  end

  resources :likes
  root 'users#index'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  devise :omniauthable, omniauth_providers: %i[facebook]

  validates :first_name, presence: true
  validates :last_name, presence: true

  has_many :friendships, inverse_of: :user, dependent: :destroy
  has_many :friends, through: :friendships

  has_many :posts
  has_many :comments
  has_many :likes

  has_one_attached :avatar
  # @book = @author.books.build(published_at: Time.now,
  # book_number: "A12345")

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.first_name = auth.info.first_name  
      user.first_name = auth.info.last_na,e # assuming the user model has a name
      # If you are using confirmable and the provider(s) you use validate emails, 
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super

    UserMailer.with(user: @user).welcome_email.deliver_later if @user.save
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = User.find(current_user.id)
    @users = User.last(20)

    @send_requests = @user.friendships
    # { |f| f.friend.first_name }
    # send requests equal user_id = current_user
    @recieved_requests = Friendship.where(friend_id: current_user.id)
    # recievedc requests equal where other users add a friend therefore they
    # added the current_user in the friend_id column

    @friends = @send_requests.map(&:friend_id)
    @friends += @recieved_requests.map(&:user_id)
    @friends.uniq!

    @posts = Post.last(10)
  end

  def show
    @user = User.find(params[:id])

    @posts = @user.posts.last(10)
  end

  def update
    @user = User.find(params[:id])

    redirect_to @user if @user.update(user_params)
  end

  private

  def user_params
    params.require(:user).permit(:avatar, :info)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<h1 class="box is-centered columns is-size-3 m-3"> Welcome <%= @user.first_name %>! </h1>

<h3 class="columns is-centered is-size-4 m-3 bold"> Friends: </h3>
<% @send_requests.each do |f| %>
  <% if f.accepted_request %>
    <div class="columns is-centered m-2">
      <%= f.friend.first_name %></br>
    </div>
  <% end %>
<% end %>

<% @recieved_requests.each do |f| %>
  <% if f.accepted_request %>
    <div class="columns is-centered m-2">
      <%= f.friend.first_name %></br>
    </div>
  <% end %>
<% end %>

<h3 class="columns is-centered is-size-4 m-3"> Your send friend requests: </h3>
<% @send_requests.each do |f| %>
  <% next if f.accepted_request %>
    <div class="columns is-centered m-2">
      <%= f.friend.first_name %></br>
    </div>
<% end %>

<h3 class="columns is-centered is-size-4 m-3"> Pending friend requests: </h3>
<% @recieved_requests.each do |f| %>
  <% next if f.accepted_request %>
  <div class="columns is-centered m-2">
    <%= link_to f.user.first_name, user_path(f.user_id) %> 
    <%= form_with(url: friendship_path(f.id), method: "patch") do |form| %>
      <%= form.submit "Accept", :class => 'button is-primary is-small ml-2' %>
      <%= form.submit "Decline", :class => 'button is-danger is-small ml-2' %>
    <% end %>
  </div>
<% end %>

<h3 class="box columns is-centered is-size-4 m-5">Latest Posts</h3>
<ul>
  <% @posts.each do |post| %>
    <li class="columns is-centered m-3">
      <%= link_to post.title, post_path(post) %>
    </li>
  <% end %>
</ul>

<h3 class="box columns is-centered is-size-4 m-5"> Latest Users </h3>
<% @users.each do |u| %>
  <%= next if @friends.include?(u.id) || current_user.id == u.id %>
  <div class="columns is-centered m-3">
    <%= link_to u.first_name, user_path(u) %>
    <%= link_to u.last_name, user_path(u), :class => "ml-2"  %>
    <%= form_with model: [ @user, @user.friendships.build ]  do |form| %>
        <%= form.hidden_field :accepted_request, value: false %>
        <%= form.hidden_field :friend_id, value: u.id %>
        <%= form.submit "Send Friend Request", :class => 'button is-primary is-small ml-2'%>
    <% end %>
  </div>
<% end %>

app/views/users/show.html.erb
<% if current_user.id == params[:id].to_i %>
  <h1 class="box columns is-centered is-size-4"> This is your profile, <%= @user.first_name %>!</h1>
<% else %>
  <h1 class="box columns is-centered is-size-4"> This is the profile of <%= @user.first_name %>!</h1>
<% end %>

<% if @user.avatar.attached? %>
  <div class="columns is-centered is-round mt-4">
    <%= image_tag @user.avatar %>
  </div>
<% end %>

<div class="columns is-centered">
  <%= @user.info if @user.info %>
</div>

<h2 class="box columns is-centered is-size-4"> Recent Posts </h2>
<% @posts.each do |post| %>
  <li>
    <ul class="columns is-centered mt-4">
      <%= link_to post.title, post_path(post) %>
    </ul>
  </li>
<% end %>

<% if current_user.id == params[:id].to_i %>
  <h2 class="box columns is-centered is-size-4 mt-6"> Update your profile here! </h2>
  <%= form_with model: @user do |form| %>
    <div class="columns is-centered mt-4">
      <%= form.text_area :info, placeholder: 'Write something about yourself!' %>
    </div>
    <div class="columns is-centered mt-4 file">
      <%= form.file_field :avatar %>
    </div>
    <div class="columns is-centered mt-4">
      <%= form.submit "Update your Profile Information!", :class => 'button is-primary' %>
    </div>
  <% end %>
<% end %>