config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: %i[index show update] do
    resources :friendships, only: %i[create]
  end

  resources :friendships, only: %i[update]

  resources :posts, only: %i[index show new create] do
    resources :comments, only: %i[show new create]
  end

  resources :likes
  root 'users#index'
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  has_many :likes
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(current_user.id)

    @friendships = Friendship.where(friend_id: current_user.id, accepted_request: true)
    @friends = Friendship.where(user_id: current_user.id, accepted_request: true)

    @friendships = @friendships.map(&:friend_id)
    @friendships += @friends.map(&:friend_id)

    @posts = Post.includes(comments: [:commenter]).where(user_id: current_user.id).or(Post.where(user_id: @friendships)).limit(10).order(created_at: :desc)
  end

  def show
    @post = Post.find(params[:id])

    @user_likes = @post.likes.map(&:user_id)
  end

  def new
    @post = Post.new
  end

  def create
    @post = User.find(current_user.id).posts.new(post_params)

    if @post.save
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
<h1 class="columns is-centered is-size-1 has-text-weight-bold">Recent Posts</h1>

<div>
  <% @posts.each do |post| %>
    <%= render 'shared/post_content', :post => post %>
    <div class="columns is-centered">
      <%= link_to "View this post!", post_path(post) %>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<h1 class="columns is-centered is-size-1 has-text-weight-bold>">Write a new Post</h1>

<%= form_with model: @post do |form| %>
  <div class="columns is-centered margin-bot">
    <%= form.text_field :title, placeholder: "Your title!" %>
  </div>

  <div class="columns is-centered mt-4">
    <%= form.text_area :body, placeholder: "What is going on right now?" %>
  </div>
  

  <div class="columns is-centered mt-4">
    <%= form.submit :class => 'button is-primary' %>
  </div>
<% end %>

app/views/posts/show.html.erb
<%= render 'shared/post_content', :post => @post %>

<p class="columns is-centered">
  Liked by<% @post.likes.each do |like| %>
    <%= like.user.first_name %>
  <% end %>
</p>

<% if @user_likes.include?(current_user.id) %>
<% else %>
  <div class="columns is-centered is-size-4">
    Like this Post!
  </div>
  <%= form_with(url: likes_path, method: "post") do |form| %>
    <p class="columns is-centered">
      <%= form.hidden_field :post_id, value: @post.id %>
      <%= form.submit "Like!", :class => 'button is-primary' %>
    </p>
  <% end %>
<% end %>

<div class="columns is-centered is-size-4 mt-4">
  Add a comment:
</div>

<%= form_with model: [ @post, @post.comments.build ] do |form| %>
  <div class="columns is-centered mt-4">
    <%= form.text_area :body %>
  </div>
  <div class="columns is-centered mt-4">
    <%= form.submit :class => 'button is-primary is-medium' %>
  </div>
<% end %>


<div class="columns is-centered mt-4"><%= link_to "Back to your timeline", posts_path %></div>