config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: %i[index show update] do
    resources :friendships, only: %i[create]
  end

  resources :friendships, only: %i[update]

  resources :posts, only: %i[index show new create] do
    resources :comments, only: %i[show new create]
  end

  resources :likes
  root 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, presence: true, length: { minimum: 10 }

  belongs_to :commenter, class_name: 'User'
  belongs_to :post
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  validates :accepted_request, inclusion: [true, false]

  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  has_many :likes
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  devise :omniauthable, omniauth_providers: %i[facebook]

  validates :first_name, presence: true
  validates :last_name, presence: true

  has_many :friendships, inverse_of: :user, dependent: :destroy
  has_many :friends, through: :friendships

  has_many :posts
  has_many :comments
  has_many :likes

  has_one_attached :avatar
  # @book = @author.books.build(published_at: Time.now,
  # book_number: "A12345")

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.first_name = auth.info.first_name  
      user.first_name = auth.info.last_na,e # assuming the user model has a name
      # If you are using confirmable and the provider(s) you use validate emails, 
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    @comment.commenter_id = current_user.id

    @comment.save

    redirect_to post_path(@post)
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def new
    @friendship = Friendship.new
  end

  def create
    @user = User.find(current_user.id)
    @friendship = @user.friendships.new(friendships_params)

    @friendship.save

    redirect_to root_path
  end

  def update
    @friendship = Friendship.find(params[:id])

    if params[:commit] == 'Accept'
      @friendship.accepted_request = true
      @friendship.save
    else
      Friendship.destroy(params[:id])
    end

    redirect_to root_path
  end

  private

  def friendships_params
    params.require(:friendship).permit(:accepted_request, :friend_id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def new
    @like = Like.new
  end

  def create
    @post = Post.find(params[:post_id])
    @like = @post.likes.new
    @like.user_id = current_user.id

    @like.save

    redirect_to post_path(@post)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(current_user.id)

    @friendships = Friendship.where(friend_id: current_user.id, accepted_request: true)
    @friends = Friendship.where(user_id: current_user.id, accepted_request: true)

    @friendships = @friendships.map(&:friend_id)
    @friendships += @friends.map(&:friend_id)

    @posts = Post.includes(comments: [:commenter]).where(user_id: current_user.id).or(Post.where(user_id: @friendships)).limit(10).order(created_at: :desc)
  end

  def show
    @post = Post.find(params[:id])

    @user_likes = @post.likes.map(&:user_id)
  end

  def new
    @post = Post.new
  end

  def create
    @post = User.find(current_user.id).posts.new(post_params)

    if @post.save
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = User.find(current_user.id)
    @users = User.last(20)

    @send_requests = @user.friendships
    # { |f| f.friend.first_name }
    # send requests equal user_id = current_user
    @recieved_requests = Friendship.where(friend_id: current_user.id)
    # recievedc requests equal where other users add a friend therefore they
    # added the current_user in the friend_id column

    @friends = @send_requests.map(&:friend_id)
    @friends += @recieved_requests.map(&:user_id)
    @friends.uniq!

    @posts = Post.last(10)
  end

  def show
    @user = User.find(params[:id])

    @posts = @user.posts.last(10)
  end

  def update
    @user = User.find(params[:id])

    redirect_to @user if @user.update(user_params)
  end

  private

  def user_params
    params.require(:user).permit(:avatar, :info)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFakebook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar" role="navigation" aria-label="main navigation">
      <% if current_user %>
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'button is-danger is-small m-1' %>
        <%= link_to "Your Profile", user_path(current_user), :class => 'button is-link is-small m-1' %>
        <%= link_to "Create a Post", new_post_path, :class => 'button is-link is-small m-1'%>
        <%= link_to "Timeline", posts_path, :class => 'button is-link is-small m-1' %>
      <% else %>
        <%= link_to "Login", new_user_session_path, :class => 'button is-danger is-small m-1' %>
      <% end %>
        <%= link_to "Home", root_path, :class => 'button is-primary is-small m-1' %>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/shared/_post_content.html.erb
<div class="columns is-centered is-size-2 box">
  <%= link_to post.title, post_path(post) %>
</div>

<p class="columns is-centered is-size-5">
  by: <%= link_to post.user.first_name, user_path(post.user) %>
</p>
<div class="columns is-centered is-size-2">
  <%= post.body %>
</div>
<% if post.comments.any? %>
<div class="columns is-centered is-size-4 mt-5">
  Comments:
</div>
  <% post.comments.each do |comment| %>
      <div class="columns is-centered mt-3"><%= comment.body %></div>
      <div class="columns is-centered mt-1 is-italic">by: <%= comment.commenter.first_name %></div>
  <% end %>
<% end %>
<div class="columns is-centered is-size-4 mt-4">
  Total Likes: <%= post.likes.count %>
</div>